name=ELF Namespace Import
description=Imports an ELF binary into the current project and applies namespaces to symbols in both the existing and newly imported binary to prevent name clashes.
author=Buttje
createdOn=03/04/2026
version=@extversion@
